[package]
name = "suspend_fn"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
suspend_fn_proc_macro = {path ="../suspend_fn_proc_macro"}


[dev-dependencies]
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
